# Generated by Django 3.2.18 on 2024-01-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='power_reserve',
            field=models.CharField(choices=[('full', 'Полный бак'), ('50km', '50 км'), ('100km', '100 км')], max_length=30, verbose_name='Запас хода'),
        ),
    ]
