# Generated by Django 3.2.18 on 2024-01-10 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarVarious',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Уникальный слаг')),
            ],
            options={
                'verbose_name': 'Разное',
                'verbose_name_plural': 'Разное',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='child_seat',
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.CharField(choices=[('BelkaCar', 'BelkaCar'), ('YandexDrive', 'ЯндексДрайв'), ('CityDrive', 'Ситидрайв'), ('DelyMobil', 'Делимобиль')], max_length=30, verbose_name='Название компании каршеринга'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_car',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('universak', 'Универсал'), ('kupe', 'Купе'), ('minivan', 'Минивен'), ('vnedorojnik', 'Внедорожник')], max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='coordinatescar',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Допустимый диапазон: -90.0 до 90.0', validators=[django.core.validators.MaxValueValidator(limit_value=90.0), django.core.validators.MinValueValidator(limit_value=-90.0)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinatescar',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Допустимый диапазон: -180.0 до 180.0', validators=[django.core.validators.MaxValueValidator(limit_value=180.0), django.core.validators.MinValueValidator(limit_value=-180.0)], verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='car',
            name='various',
            field=models.ManyToManyField(related_name='car_various', to='cars.CarVarious', verbose_name='Разное'),
        ),
    ]
