# Generated by Django 3.2.18 on 2024-01-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20240110_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rating',
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.CharField(choices=[('BelkaCar', 'BelkaCar'), ('YandexDrive', 'ЯндексДрайв'), ('CityDrive', 'Ситидрайв'), ('DeliMobil', 'Делимобиль')], max_length=30, verbose_name='Название компании каршеринга'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_reserve',
            field=models.CharField(choices=[('full', 'Полный бак'), ('50km', '50 км'), ('100km', '100 км')], max_length=30, verbose_name='Запас хода'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_car',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('universal', 'Универсал'), ('coupe', 'Купе'), ('minivan', 'Минивен'), ('suv', 'Внедороджник')], max_length=30, verbose_name='Тип'),
        ),
    ]
