# Generated by Django 3.2.18 on 2024-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_power_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.CharField(choices=[('BelkaCar', 'BelkaCar'), ('YandexDrive', 'ЯндексДрайв'), ('CityDrive', 'Ситидрайв'), ('DeliMobil', 'Делимобиль')], max_length=30, verbose_name='Название компании каршеринга'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_car',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('universal', 'Универсал'), ('coupe', 'Купе'), ('minivan', 'Минивен'), ('suv', 'Внедороджник')], max_length=30, verbose_name='Тип'),
        ),
    ]
