# Generated by Django 3.2.18 on 2024-01-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240113_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
    ]
