# Generated by Django 3.2.18 on 2024-01-11 14:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0, help_text='Допустимый диапазон: -90.0 до 90.0', validators=[django.core.validators.MaxValueValidator(limit_value=90.0), django.core.validators.MinValueValidator(limit_value=-90.0)], verbose_name='Широта')),
                ('longitude', models.FloatField(default=0.0, help_text='Допустимый диапазон: -180.0 до 180.0', validators=[django.core.validators.MaxValueValidator(limit_value=180.0), django.core.validators.MinValueValidator(limit_value=-180.0)], verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Координата',
                'verbose_name_plural': 'Координаты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Адрес электронной почты', max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Введите корректный адрес электронной почты.')], verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(help_text='Имя', max_length=100, validators=[users.validators.name_surname_validator], verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия', max_length=100, validators=[users.validators.name_surname_validator], verbose_name='Фамилия')),
                ('password_reset_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код для сброса пароля')),
                ('password_reset_attempts', models.IntegerField(default=0, verbose_name='Счётчик количество попыток сброса пароля.')),
                ('coordinates', models.OneToOneField(blank=True, help_text='Укажите координаты пользователя.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='users.usercoordinates', verbose_name='Координаты пользователя.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
