# Generated by Django 3.2.18 on 2024-01-10 05:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0, help_text='Допустимый диапазон: -90.0 до 90.0', validators=[django.core.validators.MaxValueValidator(limit_value=90.0), django.core.validators.MinValueValidator(limit_value=-90.0)], verbose_name='Широта')),
                ('longitude', models.FloatField(default=0.0, help_text='Допустимый диапазон: -180.0 до 180.0', validators=[django.core.validators.MaxValueValidator(limit_value=180.0), django.core.validators.MinValueValidator(limit_value=-180.0)], verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Координата',
                'verbose_name_plural': 'Координаты',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='coordinates',
            field=models.OneToOneField(blank=True, help_text='Укажите координаты пользователя.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='users.usercoordinates', verbose_name='Координаты пользователя.'),
        ),
    ]
